# -*- coding: utf-8 -*-
"""Precipitation Annual Change Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TS3WUglQA4mpXiRbabhGYhNExnYOEZQ6
"""

!pip install --upgrade xee

!pip install -U geemap

import ee

ee.Authenticate()
ee.Initialize(
    project = 'ee-lavibas23',
    opt_url = 'https://earthengine-highvolume.googleapis.com'
)

import geemap

map = geemap.Map()
map

roi = map.draw_last_feature.geometry()
roi

border = (
    ee.FeatureCollection("USDOS/LSIB_SIMPLE/2017")
    .filterBounds(roi)
    .geometry().simplify(100)
)

map.addLayer(border, {},'border')

gpm = (
    ee.ImageCollection("NASA/GPM_L3/IMERG_MONTHLY_V07")
    .filterDate('2015','2025')
    .select('precipitation')
    .map(
        lambda img: img.clip(border).copyProperties(img, ['system:time_start'])
    )
)

gpm.getInfo()

import xarray as xr

pr = xr.open_dataset(
    gpm,
    engine = 'ee',
    crs = 'EPSG:4326',
    scale = 0.07,
    geometry = border
)

pr = pr.sortby('time') * 730.001

import numpy as np

pr_annual = pr.resample(time = 'YE').sum('time')
pr_annual = xr.where(pr_annual == 0,  np.nan, pr_annual)

pr_annual.precipitation.plot.contourf(
    x = 'lon',
    y = 'lat',
    col = 'time',
    col_wrap = 5,
    robust = True,
    levels = 10
)

annual_change = pr_annual.diff('time')

import matplotlib.pyplot as plt

annual_change.precipitation.plot.contourf(
    x = 'lon',
    y = 'lat',
    col = 'time',
    col_wrap = 5,
    robust = True,
    levels = 20
)

plt.savefig('pr_change.png', dpi = 360, bbox_inches = 'tight')

mean_change = annual_change.mean(dim = 'time')

mean_change.precipitation.plot.contourf(
    x = 'lon',
    y = 'lat',
    robust =True,
    levels = 10
)